# Generated by Django 5.1.2 on 2024-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='weeklyvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
